# SPDX-License-Identifier: Apache-2.0
"""Forge observations and explicitly authorized effects."""

from typing import Protocol

from creatidy_kernel.core.forge import Effect, Observation, Page, Receipt, Reference


class Forge(Protocol):
    def capabilities(self) -> frozenset[str]: ...

    def identity(self, repository: Reference) -> Observation: ...

    def branch(self, repository: Reference, branch: str) -> Observation: ...

    def change(self, repository: Reference, change: Reference) -> Observation: ...

    def checks(self, repository: Reference, revision: Reference, cursor: str | None = None) -> Page: ...

    def changes(self, repository: Reference, cursor: str | None = None) -> Page: ...

    def apply(self, effect: Effect) -> Receipt: ...

    def reconcile(self, effect: Effect, known_reference: Reference | None = None) -> Receipt:
        """known_reference must come from the caller's durable accepted domain receipt."""
        ...
